export const COLORS = {
    'primary-color': '#172b4d',
    'primary-light-color': '#283c5e',
    'primary-background-color': '#ffffff',
    'secondary-background-color': '#f3f3f3',
    'secondary-color': '#007ea7',
    'seconday-light-color': '#128fb8',
    'danger-color': '#9e4770',
    'danger-light-color': '#af5881',
    'warning-color': '#ffd166ff',
    'warning-light-color': '#ffda85',
    'success-color': '#3ab795ff',
    'success-light-color': '#4bc8a6',
    'white-color': '#ffffff',
    'accent-white-color': '#edeeef',
    'black-color': '#000000',
    'disabled-color': '#d3d3d3',
    'disabled-darker-color': '#a0a0a0',
    'default-color': '#657ed4',
    'default-light-color': '#849ce9',
    // icons color
    'sales-icon-color': '#7764E4',
    'inventory-icon-color': '#F53C56',
    'cashregister-icon-color': '#11CDEF',
};
